services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432" 
  api:
    build:
      context: ./
    image: docker.io/pratyushmathur17/simpleproject
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=simple_blog_api
      - POSTGRES_PASSWORD=postgres_password
      - PORT=3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"